services:
  - type: web
    name: MEDIKART-PHP
    env: docker
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        sync: false